spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 32774

server:
  servlet:
    context-path: /uaa
  port: 5000
